import { Box, Heading, Input } from '@chakra-ui/react'
import styles from '@stock-trailer/styles/Home.module.css'
import { IInstrumentInfo } from '@stock-trailer/types'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Authorize() {
  const [instruments, setInstruments] = useState<IInstrumentInfo[]>([{
    id: '',
    qty: 0
  }]);
  return (
    <>
      <Head>
        <title>Stock - Trailer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Heading>Quick Sort - Entries</Heading>
          <Box>
            {
              instruments.map((instrument, index) => {
                return (
                  <Input value={instrument.id} onChange={(event) => {
                    const newInstruments = [
                      ...instruments
                    ]
                    newInstruments[index].id = event.target.value
                    setInstruments(newInstruments);
                  }} />
                );
              })
            }
          </Box>
        </div>
      </main>
    </>
  )
}
