import { Box, Button, Heading, Input, InputGroup, InputLeftAddon, Text } from '@chakra-ui/react'
import styles from '@stock-trailer/styles/Home.module.css'
import { IInstrumentInfo } from '@stock-trailer/types'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Router, { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import useSWR from 'swr'

const fetcher = (url: string) => fetch(url).then((res) => res.json());

const inter = Inter({ subsets: ['latin'] })

export default function Authorize() {
  const router = useRouter();
  const [submitProgress, setSubmitProgress] = useState(false);
  const [instruments, setInstruments] = useState<IInstrumentInfo[]>([{
    id: '',
    qty: 0
  }]);

  const addMoreInstrument = () => {
    const newInstruments = [...instruments, {
      id: '',
      qty: 0
    }]
    setInstruments(newInstruments);
  }

  const submitEntries = () => {
    setSubmitProgress(true)
    fetch('/api/submit', {
      method: 'POST',
      body: JSON.stringify({
        instruments
      })
    })
      .then(() => {
        setSubmitProgress(false)
      })
      .catch(() => {
        setSubmitProgress(false)
      })
  }
  const { data, error, isLoading } = useSWR('/api/user', fetcher);
  useEffect(() => {
    if (data && !data?.isLoggedIn) {
      router.push('/');
    }
  }, [data, isLoading]);
  return (
    <>
      <Head>
        <title>Stock - Trailer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Heading>Quick Sort - Entries</Heading>
        <Box mt={'32px'}>
          {
            instruments.map((instrument, index) => {
              return (
                <Box marginY={'16px'} display={'flex'} flexWrap='wrap' alignItems='center' key={`qs-${index}`} >
                  <InputGroup marginY={'8px'} width={'300px'}>
                    <InputLeftAddon children='Instrument ID' />
                    <Input placeholder='Enter' title='Instrument Id' display={'Instrument Id'} value={instrument.id} onChange={(event) => {
                      const newInstruments = [
                        ...instruments
                      ]
                      newInstruments[index].id = event.target.value
                      setInstruments(newInstruments);
                    }} />
                  </InputGroup>
                  <InputGroup marginY={'8px'} width={'300px'}>
                    <InputLeftAddon children='Quantity' />
                    <Input placeholder='Enter' value={instrument.qty} onChange={(event) => {
                      const newInstruments = [
                        ...instruments
                      ]
                      newInstruments[index].qty = +event.target.value
                      setInstruments(newInstruments);
                    }} />
                  </InputGroup>
                </Box>
              );
            })
          }
          <Box>
            <Button mr={'16px'} variant={'solid'} mt={'16px'} onClick={addMoreInstrument}>Add instrument</Button>
            <Button disabled={submitProgress} isLoading={submitProgress} variant={'solid'} mt={'16px'} onClick={submitEntries}>Submit</Button>
          </Box>
        </Box>
      </main>
    </>
  )
}
